### PR TITLE
Rainova/pr updates

### PR DESCRIPTION
**Pull request by DanVanAtta**

### CODE REVIEW

**Review by RaiNova — COMMENTED** [review]
Thanks for trying to support the coding. Using "units\generic" is intentional and based on your feedback, that nonwithdrawable.png relates to the units. 
My assets-pull-requests should also put nonwithdrawable.png into "units\generic".
Shall nonwithdrawable.png reside in misc? In that case: Let me do it on my own triplea- and assets-PRs. Already now the confusion is overwhelming and my productivity is miserable and frustrating.

**Comment by DanVanAtta** [comment]
> My assets-pull-requests should also put nonwithdrawable.png into "units\generic".

That does not look to be the case. Perhaps it was lost somewhere?

I see the new images only at: https://github.com/triplea-game/assets/tree/master/game_headed_assets/misc

**Comment by DanVanAtta** [comment]
> Shall nonwithdrawable.png reside in misc? 

I don't know if there is that much of a difference. It is a reversible decision and so we can re-organize units again however we want, whether that is in 'misc/' or a 'units/generic/'

Though, this PR is not me insisting we put the images in 'misc/', it is:
1. Getting the code to work. The asset images are in 'misc/'
2. [Improving the error message](https://github.com/RaiNova/triplea/pull/1/files#diff-d8f4fc8a21937958bc94c2be7ee0f10a9bf167e74ffe62720fa0f050336b644fR770). While it is a packaging error to have these images missing, it is still nice to know which image was missing.

Merging this would automatically update the triplea PR: https://github.com/triplea-game/triplea/pull/9509, once done then I don't think there is anything left and 9509  could be merged. =D

If you prefer to add these updates on your own and/or alter them, it's up to your discretion.

**Comment by RaiNova** [comment]
> Merging this would automatically update the triplea PR: [triplea-game#9509](https://github.com/triplea-game/triplea/pull/9509), once done then I don't think there is anything left and 9509 could be merged. =D

It‘s the common goal that unites us :wink:
Please do the PR magic - I am looking forward to build on what I learned about tripleA, IntelliJ, git(hub), and Java - thanks for your support!

**Pull request merged**
